### ISSUE TITLE
UndefinedBehaviorSanitizer: unreachable-call in boost::date_time

### ISSUE THREAD

**Issue by maflcko** [MarcoFalke/btc_nightly#8]
To reproduce on rawhide:

```
dnf install llvm clang libubsan gcc-c++ libtool make autoconf automake python3 libevent-devel boost-devel sqlite-devel      curl wget htop git vim ccache    -y && git clone https://github.com/bitcoin/bitcoin.git  --depth=1 ./bitcoin-core && cd bitcoin-core  &&  ./autogen.sh
touch /tmp/e
./configure --with-sanitizers=undefined --enable-fuzz CC=clang CXX=clang++  && make clean && make -j $(nproc)
make && FUZZ=parse_iso8601 UBSAN_OPTIONS="print_stacktrace=1:halt_on_error=1:report_error_type=1" ./src/test/fuzz/fuzz  /tmp/e
```

```
/usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/basic_string.h:278:8: runtime error: execution reached an unreachable program point
    #0 0x5642979e1d46 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>::_M_construct<boost::iterators::transform_iterator<boost::algorithm::detail::to_lowerF<char>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, boost::use_default, boost::use_default>>(boost::iterators::transform_iterator<boost::algorithm::detail::to_lowerF<char>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, boost::use_default, boost::use_default>, boost::iterators::transform_iterator<boost::algorithm::detail::to_lowerF<char>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, boost::use_default, boost::use_default>, std::input_iterator_tag) /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/basic_string.tcc
    #1 0x5642979e07a4 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>::basic_string<boost::iterators::transform_iterator<boost::algorithm::detail::to_lowerF<char>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, boost::use_default, boost::use_default>, void>(boost::iterators::transform_iterator<boost::algorithm::detail::to_lowerF<char>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, boost::use_default, boost::use_default>, boost::iterators::transform_iterator<boost::algorithm::detail::to_lowerF<char>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, boost::use_default, boost::use_default>, std::allocator<char> const&) /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/basic_string.h:764:4
    #2 0x5642979e07a4 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> boost::algorithm::detail::transform_range_copy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, boost::algorithm::detail::to_lowerF<char>>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, boost::algorithm::detail::to_lowerF<char>) /usr/include/boost/algorithm/string/detail/case_conv.hpp:116:24
    #3 0x5642979e07a4 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> boost::algorithm::to_lower_copy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::locale const&) /usr/include/boost/algorithm/string/case_conv.hpp:76:20
    #4 0x5642979e07a4 in boost::date_time::string_parse_tree<char>::string_parse_tree(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>>, unsigned int) /usr/include/boost/date_time/string_parse_tree.hpp:110:23
    #5 0x5642979e2cec in boost::date_time::special_values_parser<boost::gregorian::date, char>::sv_strings(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) /usr/include/boost/date_time/special_values_parser.hpp:91:22
    #6 0x5642979df796 in boost::date_time::special_values_parser<boost::gregorian::date, char>::special_values_parser() /usr/include/boost/date_time/special_values_parser.hpp:54:7
    #7 0x5642979de4f5 in boost::date_time::date_input_facet<boost::gregorian::date, char, std::istreambuf_iterator<char, std::char_traits<char>>>::date_input_facet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, unsigned long) /usr/include/boost/date_time/date_facet.hpp:458:14
    #8 0x5642979da6e0 in boost::date_time::time_input_facet<boost::posix_time::ptime, char, std::istreambuf_iterator<char, std::char_traits<char>>>::time_input_facet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, unsigned long) /usr/include/boost/date_time/time_facet.hpp:735:11
    #9 0x5642979d8b70 in wallet::ParseISO8601DateTime(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) src/wallet/rpc/util.cpp:26:13
    #10 0x5642971fb3bf in parse_iso8601_fuzz_target(Span<unsigned char const>) src/wallet/test/fuzz/parse_iso8601.cpp:26:35
    #11 0x564297423ea0 in std::function<void (Span<unsigned char const>)>::operator()(Span<unsigned char const>) const /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/std_function.h:591:9
    #12 0x564297423ea0 in main src/test/fuzz/fuzz.cpp:213:13
    #13 0x7f4a4f894b49 in __libc_start_call_main (/lib64/libc.so.6+0x27b49) (BuildId: 131f9d83c42aa889f22a75a9bea111d76d412a71)
    #14 0x7f4a4f894c0a in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x27c0a) (BuildId: 131f9d83c42aa889f22a75a9bea111d76d412a71)
    #15 0x5642971cb2a4 in _start (/bitcoin-core/src/test/fuzz/fuzz+0x105d2a4) (BuildId: b5c4de172da1f870e81001805cb8df1497edd702)

SUMMARY: UndefinedBehaviorSanitizer: unreachable-call /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/basic_string.h:278:8 in

**Comment by fanquake** [comment]
Will take a look
